name: build package

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Package the repo
    steps:
    - uses: actions/checkout@v3
    - run: |
        python3 --version
        python3 -m pip install --upgrade pip
        cd deploy
        pip install -r requirements.txt
        python3 ../setup.py sdist bdist_wheel