name: Continuous Deployment
on:
  repository_dispatch:
    types: deploy
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        command_timeout: 30m
        script: |
          git clone https://github.com/aissa-laribi/django-cms-jenkins temp
          cd temp
          docker stop djangocmsjenkins_web_1 djangocmsjenkins_database_default_1
          docker rmi $(docker images -q) -f
          docker-compose build web
          docker-compose up -d
          docker start djangocmsjenkins_web_1 djangocmsjenkins_database_default_1
          docker system prune
          docker stop djangocmsjenkins_web_1 djangocmsjenkins_database_default_1
          docker rmi $(docker images -q) -f
          docker start djangocmsjenkins_web_1 djangocmsjenkins_database_default_1
          mv temp/.git django-cms-jenkins/.git
          rm -rf temp



